name: Deploy Databricks DAB to Dev

on:
  push:
    branches:
      - main
    paths:
      - 'databricks/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy-dab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI v0.205+
        run: |
          pip install databricks-cli --upgrade

      - name: Set environment variables for Databricks auth
        run: echo "Environment variables set"
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.TENANT_ID }}
          DATABRICKS_HOST: ${{ secrets.HOST }}

      - name: Deploy Databricks Bundle to dev
        working-directory: databricks
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.TENANT_ID }}
          DATABRICKS_HOST: ${{ secrets.HOST }}
        run: |
          databricks bundle deploy --target dev
