name: Deploy Databricks DAB 23 to Dev

on:
  push:
    branches:
      - main
    paths:
      - 'dab_poc_gat/databricks/**'
      - '.github/workflows/main.yml'

jobs:
  deploy-dab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI v0.205+
        run: |
          pip install databricks-cli --upgrade

      - name: Debug
        run: pwd

      - name: Debug
        run: ls -lha

      - name: Debug
        run: ls -R

      - name: Deploy Databricks Bundle to dev
        env:
          DATABRICKS_HOST: ${{ secrets.HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.TENANT_ID }}
        run: |
          echo "Navigating to bundle folder..."
          cd dab_poc_gat/databricks
          echo "Running bundle deploy..."
          databricks bundle deploy --target dev
