name: Deploy Databricks DAB 23 to Dev

on:
  push:
    branches:
      - main
    paths:
      - 'dab_poc_gat/**'
      - '.github/workflows/main.yml'

jobs:
  deploy-dab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI v0.205.0 (manual binary)
        run: |
          curl -L https://github.com/databricks/cli/releases/download/v0.205.0/databricks_linux_amd64 -o $HOME/databricks
          chmod +x $HOME/databricks
          echo "$HOME" >> $GITHUB_PATH

      - name: Verify Databricks CLI version
        run: databricks version

      - name: Deploy Databricks Bundle to dev
        working-directory: dab_poc_gat
        env:
          DATABRICKS_HOST: ${{ secrets.HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.TENANT_ID }}
        run: databricks bundle deploy --target dev
