name: Deploy Databricks DAB 23 to Dev

on:
  push:
    branches:
      - main
    paths:
      - 'dab_poc_gat/**'
      - '.github/workflows/main.yml'

jobs:
  deploy-dab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI (latest stable from GitHub)
        run: |
          latest_url=$(curl -s https://api.github.com/repos/databricks/cli/releases/latest \
            | grep "browser_download_url" \
            | grep "linux_amd64.tar.gz" \
            | cut -d '"' -f 4)

          echo "Downloading: $latest_url"
          curl -L "$latest_url" -o cli.tar.gz

          mkdir -p $HOME/databricks-cli
          tar -xzf cli.tar.gz -C $HOME/databricks-cli
          chmod +x $HOME/databricks-cli/databricks

          echo "$HOME/databricks-cli" >> $GITHUB_PATH

      - name: Verify Databricks CLI version
        run: databricks version

      - name: Deploy Databricks Bundle to dev
        working-directory: dab_poc_gat
        env:
          DATABRICKS_HOST: ${{ secrets.HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.TENANT_ID }}
        run: databricks bundle deploy --target dev
