name: 'Dev deploymentss'

concurrency: 1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy bundle'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: dab_poc_gat
        env:
          DATABRICKS_HOST: ${{ secrets.HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.TENANT_ID }}
          DATABRICKS_BUNDLE_ENV: dev

  pipeline_update:
    name: 'Run pipeline update'
    runs-on: ubuntu-latest
    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle run my-job --refresh-all
        working-directory: dab_poc_gat
        env:
          DATABRICKS_HOST: ${{ secrets.HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SECRET }}
          DATABRICKS_TENANT_ID: ${{ secrets.TENANT_ID }}
          DATABRICKS_BUNDLE_ENV: dev
